# Generated by Django 5.2.5 on 2025-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_medicine_alter_signupuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
